In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/NF-UQ-NIDS-V2-Sample.csv
/kaggle/input/NF-UQ-NIDS-V2_Sample-2.csv


In [2]:
df = pd.read_csv('/kaggle/input/NF-UQ-NIDS-V2_Sample-2.csv')

In [3]:
np.unique(df['Attack'])

array(['Analysis', 'Backdoor', 'Benign', 'Bot', 'Brute Force', 'DDoS',
       'DoS', 'Exploits', 'Fuzzers', 'Generic', 'Infilteration',
       'Reconnaissance', 'Shellcode', 'Theft', 'Worms', 'injection',
       'mitm', 'password', 'ransomware', 'scanning', 'xss'], dtype=object)

In [4]:
from sklearn.preprocessing import LabelEncoder
LE1 = LabelEncoder()

In [5]:
def processX(X):
    #ip addresses are in format xxx.xxx.xxx.xxx which is not compatible with the models
    srcaddr= LE1.fit_transform(X['IPV4_SRC_ADDR'])
    X['IPV4_SRC_ADDR'] = pd.Series(srcaddr)
    dstaddr= LE1.fit_transform(X['IPV4_DST_ADDR'])
    X['IPV4_DST_ADDR'] = pd.Series(dstaddr)
    

    from sklearn.impute import SimpleImputer 
    imputer = SimpleImputer(missing_values = np.nan, strategy = 'mean')
    
    X_object = X.select_dtypes("object")
    X_int = X.select_dtypes(exclude = "object")
    X_columns = X_int.columns #this stores column names 

    imputer.fit(X_int)
    X_int = imputer.transform(X_int)
    X_int = pd.DataFrame(X_int)
    
    X_int.columns = X_columns #corrects column name
    
    X_object = X_object.fillna("unknown")
    X = X_object.join(X_int)
    from sklearn.preprocessing import StandardScaler, MinMaxScaler
    scaler = MinMaxScaler()
    # store the columns
    cols = X.columns
    
    # transform the data
    X_scaled = scaler.fit_transform(X)
    
    X_scaled = pd.DataFrame(X_scaled, columns = cols)
     
    
    return X_scaled

In [6]:
from sklearn.preprocessing import LabelEncoder
LE = LabelEncoder()

In [7]:
X=df.drop(['Attack','Dataset','Label','Attack_Class'],axis=1)
y=df['Attack']
X=processX(X)

In [8]:

# Assuming 'y_train' and 'y_test' are your original target labels
target_classes = ['Benign', 'DDoS', 'DoS', 'Brute Force']  # Replace with your 5 classes

# Filter the data
X = X[np.isin(y, target_classes)]
y = y[np.isin(y, target_classes)]


In [9]:
multilbl = LE.fit_transform(y)
y = pd.Series(multilbl)
# Access the original classes
classes = LE.classes_
# Print the mapping
for i, cls in enumerate(classes):
    print(f"{i}: {cls}")

0: Benign
1: Brute Force
2: DDoS
3: DoS


In [10]:
print(type(classes))

<class 'numpy.ndarray'>


In [11]:
from tensorflow.keras.utils import to_categorical
y_cat = to_categorical(y)

In [12]:
from sklearn.model_selection import train_test_split
x_train_dl, x_test_dl, y_train_dl, y_test_dl = train_test_split(X, y, test_size=0.2,random_state=55)
x_train_dl, x_val_dl, y_train_dl, y_val_dl = train_test_split(x_train_dl, y_train_dl, test_size=0.25,random_state=55)

In [13]:
input_feature=x_train_dl.shape[1]
output_classes=1#binary classification

In [14]:
import tensorflow as tf
from keras.callbacks import EarlyStopping
from sklearn.metrics import accuracy_score
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense, Input, Dropout, BatchNormalization, Reshape, SimpleRNN, Flatten

In [15]:
lr_schedule = tf.keras.optimizers.schedules.ExponentialDecay(
    initial_learning_rate=0.0005,
    decay_steps=10000,
    decay_rate=0.96,
    staircase=True
)

In [16]:
early_stopping = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)

In [17]:
def CNN_Model(input_feature,output_classes):
    model = Sequential([
        Input(shape=(input_feature,1)),
        LSTM(32, return_sequences=True),
        Dropout(0.5),
        BatchNormalization(),
        LSTM(64),
        Dense(output_classes, activation="sigmoid")
    ])
    model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
    return model

In [18]:

optimizer = tf.keras.optimizers.Adam(learning_rate=lr_schedule)
# model_cnn = CNN_Model()
# model_cnn.summary()

In [19]:
# history_cnn = model_cnn.fit(x_train_dl ,y_train_dl, verbose=1, epochs=100, batch_size=256,validation_data=(x_val_dl,y_val_dl),callbacks=[early_stopping])

In [20]:

# Assuming you've identified unique attack types
unique_attacks = sorted(list(set(y)))

In [21]:
num_classes = len(target_classes)

In [22]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.feature_selection import SelectFromModel

In [23]:
def train_random_forest(X, y):
    rf = RandomForestClassifier()
    rf.fit(X, y)
    return rf

In [24]:
x_train_dl

IPV4_SRC_ADDR  L4_SRC_PORT  IPV4_DST_ADDR  L4_DST_PORT  PROTOCOL  \
2829481       0.538815     0.393515       0.274445     0.001221  0.023529   
1360815       0.538838     0.518914       0.274445     0.001221  0.023529   
1566383       0.538792     0.685313       0.274746     0.001221  0.023529   
505344        0.538815     0.452522       0.274595     0.001221  0.023529   
3310944       0.538792     0.016663       0.274821     0.001221  0.023529   
...                ...          ...            ...          ...       ...   
2276609       0.538815     0.806424       0.274445     0.001221  0.066667   
3343964       0.347871     0.846952       0.234099     0.001221  0.023529   
2814049       0.538518     0.524117       0.272036     0.096834  0.023529   
175869        0.538792     0.898970       0.274595     0.001221  0.066667   
351548        0.538860     0.611612       0.274445     0.001221  0.023529   

         L7_PROTO      IN_BYTES   IN_PKTS     OUT_BYTES  OUT_PKTS  ...  \
2829481  0.028226  2.466209e-06  0.000003  0.000000e+00  0.000000  ...   
1360815  0.028226  2.466209e-06  0.000003  0.000000e+00  0.000000  ...   
1566383  0.028226  1.215233e-06  0.000000  2.050191e-07  0.000008  ...   
505344   0.028226  2.466209e-06  0.000003  0.000000e+00  0.000000  ...   
3310944  0.028226  2.466209e-06  0.000003  0.000000e+00  0.000000  ...   
...           ...           ...       ...           ...       ...  ...   
2276609  0.758065  4.646480e-07  0.000003  0.000000e+00  0.000000  ...   
3343964  0.028226  4.682222e-06  0.000011  5.878924e-06  0.000038  ...   
2814049  0.000000  3.574216e-07  0.000000  2.050191e-07  0.000008  ...   
175869   0.758065  4.646480e-07  0.000003  0.000000e+00  0.000000  ...   
351548   0.028226  2.466209e-06  0.000003  0.000000e+00  0.000000  ...   

         NUM_PKTS_512_TO_1024_BYTES  NUM_PKTS_1024_TO_1514_BYTES  \
2829481                     0.00000                          0.0   
1360815                     0.00000                          0.0   
1566383                     0.00000                          0.0   
505344                      0.00000                          0.0   
3310944                     0.00000                          0.0   
...                             ...                          ...   
2276609                     0.00000                          0.0   
3343964                     0.00003                          0.0   
2814049                     0.00000                          0.0   
175869                      0.00000                          0.0   
351548                      0.00000                          0.0   

         TCP_WIN_MAX_IN  TCP_WIN_MAX_OUT  ICMP_TYPE  ICMP_IPV4_TYPE  \
2829481        0.007813         0.000000        0.0             0.0   
1360815        0.007813         0.000000        0.0             0.0   
1566383        0.007813         0.000000        0.0             0.0   
505344         0.007813         0.000000        0.0             0.0   
3310944        0.007813         0.000000        0.0             0.0   
...                 ...              ...        ...             ...   
2276609        0.000000         0.000000        0.0             0.0   
3343964        1.000000         0.410208        0.0             0.0   
2814049        0.015625         0.000000        0.0             0.0   
175869         0.000000         0.000000        0.0             0.0   
351548         0.007813         0.000000        0.0             0.0   

         DNS_QUERY_ID  DNS_QUERY_TYPE  DNS_TTL_ANSWER  FTP_COMMAND_RET_CODE  
2829481           0.0             0.0             0.0                   0.0  
1360815           0.0             0.0             0.0                   0.0  
1566383           0.0             0.0             0.0                   0.0  
505344            0.0             0.0             0.0                   0.0  
3310944           0.0             0.0             0.0                   0.0  
...               ...             ...             ...    

In [25]:
from sklearn.feature_selection import RFE
from sklearn.ensemble import RandomForestClassifier

In [26]:
selected_features={
    'Benign': ['IPV4_SRC_ADDR','IPV4_DST_ADDR','L4_DST_PORT','L7_PROTO','OUT_BYTES','OUT_PKTS','FLOW_DURATION_MILLISECONDS','DURATION_IN','MIN_TTL','MAX_TTL','LONGEST_FLOW_PKT','MIN_IP_PKT_LEN','DST_TO_SRC_AVG_THROUGHPUT','TCP_WIN_MAX_IN','TCP_WIN_MAX_OUT'],
    'DDoS': ['IPV4_SRC_ADDR','L4_DST_PORT','L7_PROTO','IN_PKTS','OUT_BYTES','OUT_PKTS','DURATION_OUT','MIN_TTL','MAX_TTL','LONGEST_FLOW_PKT','MAX_IP_PKT_LEN','SRC_TO_DST_AVG_THROUGHPUT','DST_TO_SRC_AVG_THROUGHPUT','NUM_PKTS_UP_TO_128_BYTES','NUM_PKTS_128_TO_256_BYTES'],
    'DoS': ['IPV4_DST_ADDR','L4_DST_PORT','PROTOCOL','L7_PROTO','TCP_FLAGS','FLOW_DURATION_MILLISECONDS','DURATION_OUT','LONGEST_FLOW_PKT','SHORTEST_FLOW_PKT','MAX_IP_PKT_LEN','SRC_TO_DST_AVG_THROUGHPUT', 'NUM_PKTS_UP_TO_128_BYTES','NUM_PKTS_128_TO_256_BYTES','TCP_WIN_MAX_IN','TCP_WIN_MAX_OUT'],
    'Brute Force': ['IPV4_SRC_ADDR','IPV4_DST_ADDR','OUT_BYTES','OUT_PKTS','CLIENT_TCP_FLAGS','FLOW_DURATION_MILLISECONDS','DURATION_IN','LONGEST_FLOW_PKT','SHORTEST_FLOW_PKT','MAX_IP_PKT_LEN','SRC_TO_DST_AVG_THROUGHPUT','DST_TO_SRC_AVG_THROUGHPUT','NUM_PKTS_UP_TO_128_BYTES','NUM_PKTS_128_TO_256_BYTES','TCP_WIN_MAX_IN'],
}

In [27]:
selected_features[classes[1]]

['IPV4_SRC_ADDR',
 'IPV4_DST_ADDR',
 'OUT_BYTES',
 'OUT_PKTS',
 'CLIENT_TCP_FLAGS',
 'FLOW_DURATION_MILLISECONDS',
 'DURATION_IN',
 'LONGEST_FLOW_PKT',
 'SHORTEST_FLOW_PKT',
 'MAX_IP_PKT_LEN',
 'SRC_TO_DST_AVG_THROUGHPUT',
 'DST_TO_SRC_AVG_THROUGHPUT',
 'NUM_PKTS_UP_TO_128_BYTES',
 'NUM_PKTS_128_TO_256_BYTES',
 'TCP_WIN_MAX_IN']

In [28]:
models={}

In [29]:
# Train and evaluate for each attack type (OvR)
for i in range(0,4):#, [model,attack] in enumerate(models):

    attack=classes[i]
    # Create OvR target variable
    y_train_ovr = (y_train_dl == i).astype(int)
    y_test_ovr = (y_test_dl == i).astype(int)
    y_val_ovr = (y_val_dl == i).astype(int)
    

    print(f"Training for {attack}")
    
    print("Selecting features")
    X_train_selected=x_train_dl[selected_features[attack]]
    X_test_selected=x_test_dl[selected_features[attack]]
    X_val_selected=x_val_dl[selected_features[attack]]
    
    
    x_train_dl_rs = X_train_selected.values.reshape(X_train_selected.shape[0], X_train_selected.shape[1],1)
    x_val_dl_rs = X_val_selected.values.reshape(X_val_selected.shape[0], X_val_selected.shape[1],1)
    x_test_dl_rs = X_test_selected.values.reshape(X_test_selected.shape[0], X_test_selected.shape[1],1)
    
    print("Training CNN model")
    input_feature=X_train_selected.shape[1]
    output_classes=1#binary classification
    model = CNN_Model(input_feature,output_classes)
    model.fit(x_train_dl_rs, y_train_ovr, epochs=100, batch_size=256,validation_data=(x_val_dl_rs,y_val_ovr),callbacks=[early_stopping], verbose=1)  # Adjust epochs and batch size

    # Evaluate the model
    print("Evaluating Model")
    loss, accuracy = model.evaluate(x_test_dl_rs, y_test_ovr, verbose=1)
    print(f"Accuracy for {attack}: {accuracy}")
    models[attack]=model
    
    print("Saving Model")
    model.save(f"model_{attack}.h5")
    print("Model Saved!")


Training for Benign
Selecting features
Training CNN model
Epoch 1/100
7608/7608 ━━━━━━━━━━━━━━━━━━━━ 57s 7ms/step - accuracy: 0.9616 - loss: 0.0982 - val_accuracy: 0.9812 - val_loss: 0.0416
Epoch 2/100
7608/7608 ━━━━━━━━━━━━━━━━━━━━ 52s 7ms/step - accuracy: 0.9817 - loss: 0.0443 - val_accuracy: 0.9866 - val_loss: 0.0345
Epoch 3/100
7608/7608 ━━━━━━━━━━━━━━━━━━━━ 52s 7ms/step - accuracy: 0.9897 - loss: 0.0278 - val_accuracy: 0.9680 - val_loss: 0.0680
Epoch 4/100
7608/7608 ━━━━━━━━━━━━━━━━━━━━ 52s 7ms/step - accuracy: 0.9926 - loss: 0.0209 - val_accuracy: 0.9946 - val_loss: 0.0165
Epoch 5/100
7608/7608 ━━━━━━━━━━━━━━━━━━━━ 52s 7ms/step - accuracy: 0.9935 - loss: 0.0182 - val_accuracy: 0.9941 - val_loss: 0.0170
Epoch 6/100
7608/7608 ━━━━━━━━━━━━━━━━━━━━ 53s 7ms/step - accuracy: 0.9941 - loss: 0.0168 - val_accuracy: 0.9952 - val_loss: 0.0144
Epoch 7/100
7608/7608 ━━━━━━━━━━━━━━━━━━━━ 52s 7ms/step - accuracy: 0.9945 - loss: 0.0155 - val_accuracy: 0.9954 - val_loss: 0.0129
Epoch 8/100
7608/7

In [30]:
import tensorflow as tf

# Function to load a model from an h5 file
def load_model_from_h5(file_path):
    model = tf.keras.models.load_model(file_path)
    return model

# Load all models
models = [load_model_from_h5(f"/kaggle/working/model_{attack}.h5") for attack in classes]

# Function to make a prediction using the OvR models
def predict_class(x):
    predictions = []
    i=0
    for model in models:
        x_sel=x[selected_features[classes[i]]]
        prediction = model.predict(x_sel,verbose=0)
        predictions.append(prediction)
        i=i+1

    # Convert predictions to class probabilities
    probabilities = np.array(predictions)
    
    # Predict the class with the highest probability
    predicted_classes = np.argmax(probabilities, axis=0)

    return predicted_classes


In [31]:
predicted_class = predict_class(x_test_dl)
print("Predicted class:", predicted_class)

Predicted class: [[3]
 [3]
 [0]
 ...
 [2]
 [0]
 [3]]


In [32]:
from sklearn.metrics import precision_score, recall_score, f1_score, confusion_matrix, classification_report
# Evaluate the model
accuracy = accuracy_score(y_test_dl, predicted_class)
precision = precision_score(y_test_dl, predicted_class, average='weighted')
recall = recall_score(y_test_dl, predicted_class, average='weighted')
f1 = f1_score(y_test_dl, predicted_class, average='weighted')

confusion_mat = confusion_matrix(y_test_dl, predicted_class)
confusion_rep = classification_report(y_test_dl, predicted_class)

print("Accuracy:", accuracy)
print("Precision:", precision)
print("Recall:", recall)
print("F1-Score:", f1)
print("Confusion Matrix:\n", confusion_mat)

Accuracy: 0.9935452862103281
Precision: 0.9935524045250682
Recall: 0.9935452862103281
F1-Score: 0.9935468581062189
Confusion Matrix:
 [[250799      2    128    322]
 [     3   1234     36      0]
 [   190      0 215811   1942]
 [   140      0   1427 177104]]


In [33]:
print(confusion_rep)

              precision    recall  f1-score   support

           0       1.00      1.00      1.00    251251
           1       1.00      0.97      0.98      1273
           2       0.99      0.99      0.99    217943
           3       0.99      0.99      0.99    178671

    accuracy                           0.99    649138
   macro avg       0.99      0.99      0.99    649138
weighted avg       0.99      0.99      0.99    649138

